AWSTemplateFormatVersion: '2019-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API de Envios
Author: Muñoz, Fabio Nahuel

Resources:
  Envios:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 120
      Events:
        GetEnvio:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}
            Method: get
        GetPendientes:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        Envios:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        Movimiento:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/movimiento
            Method: post
        Entrega:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: post
        Crear:
          Type: Api
          Properties:
            Path: /crear
            Method: post